#!/usr/bin/env python3
"""Regenerate the checked-in WebP and AVIF validation corpora.

The accepted image payloads come from the encoder libraries pinned by
Cargo.lock. Generated bytes are checked in, so normal builds do not run this
tool.
"""

from __future__ import annotations

import struct
import subprocess
import tempfile
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1] / "tests" / "corpus"
C2PA_UUID = bytes.fromhex("d8fec3d61b0e483c92975828877ec481")


def run(*arguments: str) -> None:
    subprocess.run(arguments, check=True, stdout=subprocess.DEVNULL)


def riff_chunk(name: bytes, payload: bytes) -> bytes:
    return name + struct.pack("<I", len(payload)) + payload + (b"\0" if len(payload) & 1 else b"")


def append_webp(source: bytes, name: bytes, payload: bytes) -> bytes:
    contents = source + riff_chunk(name, payload)
    return contents[:4] + struct.pack("<I", len(contents) - 8) + contents[8:]


def webp_with_exif(source: bytes, payload: bytes, width: int, height: int) -> bytes:
    canvas = (width - 1).to_bytes(3, "little") + (height - 1).to_bytes(3, "little")
    contents = (
        b"WEBP"
        + riff_chunk(b"VP8X", b"\x08\0\0\0" + canvas)
        + source[12:]
        + riff_chunk(b"EXIF", payload)
    )
    return b"RIFF" + struct.pack("<I", len(contents)) + contents


def bmff_box(name: bytes, payload: bytes) -> bytes:
    return struct.pack(">I", len(payload) + 8) + name + payload


def append_to_bmff_box(source: bytes, name: bytes, payload: bytes) -> bytes:
    position = 0
    while position < len(source):
        size = struct.unpack(">I", source[position : position + 4])[0]
        if source[position + 4 : position + 8] == name:
            expanded = (
                struct.pack(">I", size + len(payload))
                + source[position + 4 : position + size]
            )
            return source[:position] + expanded + payload + source[position + size :]
        position += size
    raise ValueError(f"missing BMFF box: {name!r}")


def write(group: str, kind: str, name: str, contents: bytes) -> None:
    directory = ROOT / kind / "v1" / group
    directory.mkdir(parents=True, exist_ok=True)
    (directory / name).write_bytes(contents)


def main() -> None:
    with tempfile.TemporaryDirectory(prefix="imglean-modern-corpus-") as temporary:
        temporary = Path(temporary)
        webp = temporary / "source.webp"
        changed_webp = temporary / "changed.webp"
        avif = temporary / "source.avif"
        changed_avif = temporary / "changed.avif"
        run(
            "cargo",
            "run",
            "--locked",
            "--example",
            "generate_modern_corpus",
            "--",
            str(temporary),
        )

        webp_bytes = append_webp(webp.read_bytes(), b"JUNK", b"\0" * 4096)
        write("accepted", "webp", "provider-reduction.webp", webp_bytes)
        write(
            "accepted",
            "webp",
            "metadata.webp",
            webp_with_exif(webp_bytes, b"imglean-exif-marker", 128, 128),
        )
        write("changed", "webp", "dimensions.webp", changed_webp.read_bytes())
        write("rejected", "webp", "trailing.webp", webp_bytes + b"trailing")
        write("rejected", "webp", "truncated.webp", webp_bytes[:-3])
        write("rejected", "webp", "xmp.webp", append_webp(webp_bytes, b"XMP ", b"xmp"))
        write("rejected", "webp", "c2pa.webp", append_webp(webp_bytes, b"C2PA", b"manifest"))
        write("rejected", "webp", "animated.webp", append_webp(webp_bytes, b"ANIM", b"\0" * 6))

        avif_bytes = append_to_bmff_box(avif.read_bytes(), b"mdat", b"\0" * 2048)
        write("accepted", "avif", "provider-reduction.avif", avif_bytes)
        write("changed", "avif", "dimensions.avif", changed_avif.read_bytes())
        write("rejected", "avif", "trailing.avif", avif_bytes + b"trailing")
        write("rejected", "avif", "truncated.avif", avif_bytes[:-3])
        write("rejected", "avif", "xmp.avif", avif_bytes + bmff_box(b"free", b"application/rdf+xml"))
        write("rejected", "avif", "c2pa.avif", avif_bytes + bmff_box(b"uuid", C2PA_UUID + b"manifest"))


if __name__ == "__main__":
    main()
